### ISSUE TITLE
Suggestions for Roassal3

### ISSUE THREAD

**Issue by bergel** [ObjectProfile/Roassal2#1]
Acá algunas sugerencias para Roassal3

seria genial tener un script que combine caracteristicas de RTShapeBuilder RTShape y RTInteractionBuilder

shape := RTShape box.
shape size: [:model | self computeSizeForModel: model ].
shape if: #hasChildren color: Color red.
shape position: [:model | model position ].
shape if: #hasChildren size: 10.
shape theme: RTSuperCoolTheme.

shape popup.
shape when: TRMouseClick do: [:evt | ...].

elements := shape elementsOn: models.
elements first rawShape: RTShape ellipse.

view addAll: elements.

**Comment by akevalion** [comment]
Esto ya se ha pasado a Carlone

**Comment by akevalion** [comment]
Roassal3 is part of pharo 11
