### ISSUE TITLE
Add version tags and 'stable' branch

### ISSUE THREAD

**Issue by dorellang** [ObjectProfile/Roassal2#12]
Please add them for the next version release so I can easily declare a dependency on a specific Roassal version in my projects' baselines :smile:

Also it would be a good idea to have a 'stable' branch or something similar, just to make sure a random commit doesn't break the installation of other projects.

**Comment by akevalion** [comment]
Please check
https://github.com/ObjectProfile/Roassal2/releases

I have change the code, Roassal2 will be frozen.
Please use roassal3 https://github.com/ObjectProfile/Roassal3
