### ISSUE TITLE
Cyclic dependency between Roassal-Core and ExampleBrowser

### ISSUE THREAD

**Issue by pavel-krivanek** [ObjectProfile/Roassal2#15]
<a href="https://github.com/seandenigris"><img src="https://avatars3.githubusercontent.com/u/184176?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [seandenigris](https://github.com/seandenigris)**
_Monday Aug 03, 2015 at 18:35 GMT_
_Originally opened as https://github.com/moosetechnology/Moose/issues/1108_

----

Originally reported on Google Code with ID 1108

```
Package Core defines the abstract class RTObject.
Package ExampleBrowser defines the abstract class RTAbstractExample as subclass of
RTObject. 

The problem is that package Core also includes class RTMultiColoredLineExample as a
subclass of RTAbstractExample. So package ExampleBrowser requires package Core because
of RTObject, and package Core requires package ExampleBrowser because of RTAbstractExample.

The solution could be to move class RTMultiColoredLineExample to package ExampleBrowser?

This leads to cyclic dependencies, that at least in the Visualworks port lead to warnings
and bundle structure errros.

Please fill in the labels with the following information:
* Type-Defect
* Component-Roassal

```

Reported by `thomas.brodt@porabo.ch` on 2015-03-03 09:30:16

**Comment by pavel-krivanek** [comment]
<a href="https://github.com/seandenigris"><img src="https://avatars3.githubusercontent.com/u/184176?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [seandenigris](https://github.com/seandenigris)**
_Monday Aug 03, 2015 at 18:35 GMT_

----

```
Thanks! We will have a look at this
```

Reported by `alexandre.bergel` on 2015-03-03 14:04:02

**Comment by pavel-krivanek** [comment]
<a href="https://github.com/girba"><img src="https://avatars2.githubusercontent.com/u/249595?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [girba](https://github.com/girba)**
_Friday Jun 09, 2017 at 08:06 GMT_

----

@bergel can you look at this?

**Comment by akevalion** [comment]
No longer valid, roassal2 does not contains cyclic dependency
please use Roassal3 https://github.com/ObjectProfile/Roassal3
