### ISSUE TITLE
Clean the examples of Roassal

### ISSUE THREAD

**Issue by pavel-krivanek** [ObjectProfile/Roassal2#16]
<a href="https://github.com/bergel"><img src="https://avatars0.githubusercontent.com/u/393742?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [bergel](https://github.com/bergel)**
_Monday Feb 27, 2017 at 00:52 GMT_
_Originally opened as https://github.com/moosetechnology/Moose/issues/1152_

----

Agree. Not only in Overall, in general with more than 4 figure previews at the same time, they became too small.

Cheers,

Hernán

2017-02-25 10:38 GMT-03:00 Ben Coman <btc@openinworld.com>:
Just some quick feedback... in the "Moose Suite 6.0 (beta)" image from PharoLauncher I opened World > Roassal > Roasasal Examples

Nice interface, but for the category "Grapher - Overall" I find there are too many items,
such that even the text labels are too small to read.  It might be better to split this out to a few more categories.

cheers -ben

**Comment by akevalion** [comment]
No longer valid.

please use Roassal3 https://github.com/ObjectProfile/Roassal3
