### ISSUE TITLE
RTSelectionBox

### ISSUE THREAD

**Issue by pavel-krivanek** [ObjectProfile/Roassal2#18]
<a href="https://github.com/bergel"><img src="https://avatars0.githubusercontent.com/u/393742?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [bergel](https://github.com/bergel)**
_Friday Mar 03, 2017 at 22:03 GMT_
_Originally opened as https://github.com/moosetechnology/Moose/issues/1156_

----

Should be available from the Menu in the playground

**Comment by pavel-krivanek** [comment]
<a href="https://github.com/klaranosan"><img src="https://avatars0.githubusercontent.com/u/17482490?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [klaranosan](https://github.com/klaranosan)**
_Friday Mar 16, 2018 at 13:11 GMT_

----

Hi alex 

Did you made progress on this issue? We are trying to clean the issues and you can help us to reduce the number of issues by closing the ones you know have been done or will not be done afterall.

The opendev teams

**Comment by akevalion** [comment]
Update we have RSElasticBoxInteraction in roassal3 https://github.com/ObjectProfile/Roassal3
I will close this issue because cleaning process and roassal2 will be frozen
