### ISSUE TITLE
Improvement of Roassal

### ISSUE THREAD

**Issue by pavel-krivanek** [ObjectProfile/Roassal2#19]
<a href="https://github.com/bergel"><img src="https://avatars0.githubusercontent.com/u/393742?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [bergel](https://github.com/bergel)**
_Tuesday Mar 21, 2017 at 20:15 GMT_
_Originally opened as https://github.com/moosetechnology/Moose/issues/1163_

----

we should eventually also get rid of this nonsense
 headStart: RTNoDecorationShape asHead;
   headEnd: RTNoDecorationShape asTail;

… the method should correctly convert it to the proper head/tail… the user shouldn't be bothered by it

**Comment by bergel** [comment]
Not very relevant
