### ISSUE TITLE
GraphViz layout?

### ISSUE THREAD

**Issue by pavel-krivanek** [ObjectProfile/Roassal2#20]
<a href="https://github.com/bergel"><img src="https://avatars0.githubusercontent.com/u/393742?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [bergel](https://github.com/bergel)**
_Friday Mar 24, 2017 at 17:28 GMT_
_Originally opened as https://github.com/moosetechnology/Moose/issues/1165_

----

Check if `RTGraphVizLayoutPlugin` works

**Comment by akevalion** [comment]
Update we have RSGraphVizLayout in roassal3 https://github.com/ObjectProfile/Roassal3
I will close this issue because cleaning process and roassal2 will be frozen
