### ISSUE TITLE
Issue when computing the number of lines of code per functions and methods in Python

### ISSUE THREAD

**Issue by pavel-krivanek** [ObjectProfile/Roassal2#21]
<a href="https://github.com/bergel"><img src="https://avatars0.githubusercontent.com/u/393742?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [bergel](https://github.com/bergel)**
_Tuesday Apr 18, 2017 at 16:30 GMT_
_Originally opened as https://github.com/moosetechnology/Moose/issues/1182_

----

The following GitHub produces some functions and methods that do not have a number of lines of code:
`https://github.com/radio-astro-tools/spectral-cube`

**Comment by akevalion** [comment]
Not sure if this is part of roassal2
Please use roassal3 https://github.com/ObjectProfile/Roassal3
I will close this issue because cleaning process and roassal2 will be frozen
