### ISSUE TITLE
Something weird in the way fonts are looked up

### ISSUE THREAD

**Issue by pavel-krivanek** [ObjectProfile/Roassal2#22]
<a href="https://github.com/bergel"><img src="https://avatars0.githubusercontent.com/u/393742?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [bergel](https://github.com/bergel)**
_Tuesday Apr 18, 2017 at 16:37 GMT_
_Originally opened as https://github.com/moosetechnology/Moose/issues/1183_

----

Consider the following code:
```Smalltalk
v := RTView new.
lbl := RTLabel new fontName: 'Bitmap DejaVu Sans'; elementOn: 'Hello World'.
v add: lbl.
v
```
It produces what is shown on the screenshot.

However, what is displayed is not DejaVu Sans. E.g., compare the "e" with https://www.fontsquirrel.com/fonts/dejavu-sans
![ejwvyesogyaqanc7sjdhhl_xgj2aiujarmhaugp696zv-t7igadyrww-5wqwhzp1scvjfcsszem9ndnex5spxxczy6pxbjybsbtccszbvcee5uarhqid18qtqm8wwdunnnusnbd_lcos-nqqplxsanm3ir4_wtuogw](https://cloud.githubusercontent.com/assets/393742/25142111/2351225c-243c-11e7-84e5-aee278e86782.png)

**Comment by pavel-krivanek** [comment]
<a href="https://github.com/bergel"><img src="https://avatars0.githubusercontent.com/u/393742?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [bergel](https://github.com/bergel)**
_Tuesday Apr 18, 2017 at 17:05 GMT_

----

A bit more on the font.
```Smalltalk
font := FreeTypeFont fromFile: '/Library/Fonts/Bodoni Ornaments.ttf' pointSize: 42 index: 0.

morph := StringMorph contents: 'Hello World' font: font.

morph openInWindow 

```

**Comment by bergel** [comment]
We can now do:
```Smalltalk
v := RTView new.

('/Library/Fonts/' asFileReference children first: 15) do: [ :fr |
    rawFont := FreeTypeFont fromFile: fr fullName pointSize: 10 index: 0.
    v add: (RTLabel new height: 4; rawFont: rawFont; elementOn: fr basename) ].

RTVerticalLineLayout on: v elements.
v @ RTDraggableView.
v
```

<img width="1331" alt="image" src="https://user-images.githubusercontent.com/393742/49094240-8c479700-f244-11e8-9d46-d60f2abfb897.png">
