### ISSUE TITLE
Have a better set of color palette

### ISSUE THREAD

**Issue by pavel-krivanek** [ObjectProfile/Roassal2#24]
<a href="https://github.com/bergel"><img src="https://avatars0.githubusercontent.com/u/393742?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [bergel](https://github.com/bergel)**
_Monday Apr 24, 2017 at 10:54 GMT_
_Originally opened as https://github.com/moosetechnology/Moose/issues/1188_

----

There are some good ideas here: https://github.com/d3/d3-scale-chromatic

**Comment by akevalion** [comment]
Update we have RSColorPalette  and NSScale for color palettes.
Please use roassal3 https://github.com/ObjectProfile/Roassal3
I will close this issue because cleaning process and roassal2 will be frozen
