### ISSUE TITLE
RTRDatasets needs to be updated

### ISSUE THREAD

**Issue by pavel-krivanek** [ObjectProfile/Roassal2#26]
<a href="https://github.com/bergel"><img src="https://avatars0.githubusercontent.com/u/393742?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [bergel](https://github.com/bergel)**
_Thursday May 04, 2017 at 14:37 GMT_
_Originally opened as https://github.com/moosetechnology/Moose/issues/1197_

----

Apparently, the structure of the meta-information have changed. The class needs to be updated

**Comment by pavel-krivanek** [comment]
<a href="https://github.com/SergeStinckwich"><img src="https://avatars0.githubusercontent.com/u/327334?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [SergeStinckwich](https://github.com/SergeStinckwich)**
_Wednesday May 10, 2017 at 16:00 GMT_

----

Yes apparently they move from row 4 to row 6 for the URL

**Comment by akevalion** [comment]
No longer valid
Please use roassal3 https://github.com/ObjectProfile/Roassal3
I will close this issue because cleaning process and roassal2 will be frozen
