### ISSUE TITLE
GLMPNGExportingAction and GLMPNGExporting2Action are horrible names

### ISSUE THREAD

**Issue by pavel-krivanek** [ObjectProfile/Roassal2#27]
<a href="https://github.com/bergel"><img src="https://avatars0.githubusercontent.com/u/393742?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [bergel](https://github.com/bergel)**
_Friday May 05, 2017 at 18:39 GMT_
_Originally opened as https://github.com/moosetechnology/Moose/issues/1199_

----

```Smalltalk
titleExtension
	^ 'PNG with scale'	
```
is obscure. Maybe something like _visible part_ and not _scale_

thanks Juraj for having spotted it!

**Comment by akevalion** [comment]
No longer valid, we have RSInteractiveExporter with some names to export the current visualization in the inspector
Please use roassal3 https://github.com/ObjectProfile/Roassal3
I will close this issue because cleaning process and roassal2 will be frozen
