### ISSUE TITLE
Way to reuse Layout results

### ISSUE THREAD

**Issue by pavel-krivanek** [ObjectProfile/Roassal2#28]
<a href="https://github.com/bergel"><img src="https://avatars0.githubusercontent.com/u/393742?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [bergel](https://github.com/bergel)**
_Thursday May 11, 2017 at 14:51 GMT_
_Originally opened as https://github.com/moosetechnology/Moose/issues/1202_

----

Applying a layout make takes time. It would be great to be able to save node positions and apply them again. This could be done, for example, using a hook in `RTLayout`.

**Comment by akevalion** [comment]
No longer valid
Please use roassal3 https://github.com/ObjectProfile/Roassal3
I will close this issue because cleaning process and roassal2 will be frozen
