### ISSUE TITLE
Layered TreeLayout does not align elements on the top

### ISSUE THREAD

**Issue by pavel-krivanek** [ObjectProfile/Roassal2#29]
<a href="https://github.com/girba"><img src="https://avatars2.githubusercontent.com/u/249595?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [girba](https://github.com/girba)**
_Friday Jun 09, 2017 at 08:32 GMT_
_Originally opened as https://github.com/moosetechnology/Moose/issues/1222_

----

Take a look at this script:
http://ws.stfx.eu/54G9IO1XX4R2

The issue is that instead of aligning the top left, it kind of centers the entities from the same layer.

This used to work properly, and the tree algorithm did not change. So something must have changed not too long ago related to translations.

**Comment by bergel** [comment]
For the horizontal layout, it seems to works properly:
```Smalltalk
view := RTMondrian new.
view shape rectangle width: [:x | x * 2].
view nodes: (1 to: 99).
view edges connectFrom: [ :x | x // 5 ].
view layout horizontalTree layered.
view.
```
<img width="847" alt="image" src="https://user-images.githubusercontent.com/393742/49088453-11787f00-f238-11e8-9835-40fec8f1a32b.png">

**Comment by bergel** [comment]
I have just fixed the issue:

```Smalltalk
view := RTMondrian new.
view shape rectangle height: [:x | x * 2].
view nodes: (1 to: 99).
view edges connectFrom: [ :x | x // 5 ].
view layout tree layered.
view.
```

<img width="849" alt="image" src="https://user-images.githubusercontent.com/393742/49088698-96fc2f00-f238-11e8-8fe2-568b38bc1945.png">

In version 2dd177e0
@girba
