### ISSUE TITLE
Script of the day

### ISSUE THREAD

**Issue by pavel-krivanek** [ObjectProfile/Roassal2#30]
<a href="https://github.com/bergel"><img src="https://avatars0.githubusercontent.com/u/393742?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [bergel](https://github.com/bergel)**
_Tuesday Jun 13, 2017 at 17:00 GMT_
_Originally opened as https://github.com/moosetechnology/Moose/issues/1230_

----

Edge width indicating dependence between packages.

Here is an examples for classes:
```Smalltalk
b := RTMondrian new.
b shape circle size: 20; color: Color red trans.
b nodes: RTObject withAllSubclasses.

b shape line color: Color blue trans.
es := b edges connectToAll: #dependentClasses.
b layout force charge: -500.
b normalizer 
    edges: es;
    normalizeLineWidth: [ :from :to | 
        | outgoingRef |
        outgoingRef := (from methods flatCollect: [ :cm | cm literals select: [ :l | l class == GlobalVariable ] ]) groupedBy: #value.
        (outgoingRef keys includes: to)
            ifTrue: [ (outgoingRef at: to) size ]
            ifFalse: [ 0 ] ] min: 0.2 max: 10.
b
```

**Comment by pavel-krivanek** [comment]
<a href="https://github.com/jecisc"><img src="https://avatars1.githubusercontent.com/u/9519971?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jecisc](https://github.com/jecisc)**
_Wednesday Jun 14, 2017 at 08:26 GMT_

----

Is there an issue here?

If you wish to keep this snippet maybe a Gist or a Wiki would be better.

**Comment by bergel** [comment]
Much better version of the script:

```Smalltalk
b := RTMondrian new.
b shape circle size: 20; color: Color red trans.
b nodes: RTObject withAllSubclasses.

b shape line color: Color blue trans.
es := b edges connectToAll: #dependentClasses.
b layout force charge: -500.
b normalizer 
    edges: es;
    normalizeLineWidthBasedOnOccurences: #dependentClassesWithOccurences.
b
```

**Comment by bergel** [comment]
Send to both VW-list and discord on 27/11/2018
