### ISSUE TITLE
We need a way to not have overlapped elements

### ISSUE THREAD

**Issue by pavel-krivanek** [ObjectProfile/Roassal2#31]
<a href="https://github.com/bergel"><img src="https://avatars0.githubusercontent.com/u/393742?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [bergel](https://github.com/bergel)**
_Saturday Jun 17, 2017 at 12:40 GMT_
_Originally opened as https://github.com/moosetechnology/Moose/issues/1231_

----

There are some existing algorithms:
http://www.sciencedirect.com/science/article/pii/S0020025507000989
http://rp-www.cs.usyd.edu.au/~visual/valacon/pdf/papers/APVIS05-UsingSpringToRemoveNodeOverlapping.pdf

We need a solution for this. It is a recurrent complain.

**Comment by akevalion** [comment]
This is solved with RSGraphVizLayout in roassal3
Please use roassal3 https://github.com/ObjectProfile/Roassal3
I will close this issue because cleaning process and roassal2 will be frozen
