### ISSUE TITLE
RTBorderAttachPoint has glitchy behavior when offset is used

### ISSUE THREAD

**Issue by pavel-krivanek** [ObjectProfile/Roassal2#32]
<a href="https://github.com/peteruhnak"><img src="https://avatars3.githubusercontent.com/u/1276328?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [peteruhnak](https://github.com/peteruhnak)**
_Tuesday Jun 20, 2017 at 13:49 GMT_
_Originally opened as https://github.com/moosetechnology/Moose/issues/1234_

----

RTBorderAttachPoint has glitchy behavior when offset is used.

```smalltalk
| v e1 e2 l1 l2|
v := RTView new.

e1 := RTLabel new elementOn: #RTBorderAttachPoint, ' left'.
e2 := RTLabel new elementOn: #RTBorderAttachPoint, ' right'.
e2 translateBy: 500 @ 0.
v add: e1; add: e2.
l1 := RTLine new
    attachPoint: (RTBorderAttachPoint new offset: 20);
    edgeFrom: e1 to: e2.
l2 := RTLine new
    attachPoint: (RTBorderAttachPoint new offset: 20);
    edgeFrom: e1 to: e2.
v add: l1; add: l2.

v elements @ RTDraggable.

^ v
```

![glitch](https://user-images.githubusercontent.com/1276328/27336502-0a7e3678-55d0-11e7-9257-ba36fffc1ee6.png)

![ok](https://user-images.githubusercontent.com/1276328/27336503-0b109392-55d0-11e7-8b93-0629b9933a98.png)

**Comment by akevalion** [comment]
This has been fixed with RSBorderAttachPoint
Please use roassal3 https://github.com/ObjectProfile/Roassal3
I will close this issue because cleaning process and roassal2 will be frozen
