### ISSUE TITLE
Text is not centered for very small font size

### ISSUE THREAD

**Issue by pavel-krivanek** [ObjectProfile/Roassal2#33]
<a href="https://github.com/bergel"><img src="https://avatars0.githubusercontent.com/u/393742?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [bergel](https://github.com/bergel)**
_Wednesday Jun 21, 2017 at 14:02 GMT_
_Originally opened as https://github.com/moosetechnology/Moose/issues/1240_

----

```Smalltalk
b := RTMondrian new.
b shape labeledBox
    borderColor: Color black;
    textHeight: 2.
    
b nodes: (1 to: 10).
b
```
![screenshot 2017-06-21 10 00 08](https://user-images.githubusercontent.com/393742/27388145-ae8586fc-5668-11e7-9cb3-a7ddd20dcbe6.png)

Probably it is a problem of `asIntegerPoint` somewhere

**Comment by akevalion** [comment]
This has been fixed in roassal3
Please use roassal3 https://github.com/ObjectProfile/Roassal3
I will close this issue because cleaning process and roassal2 will be frozen
