### ISSUE TITLE
Continous popup can be improved

### ISSUE THREAD

**Issue by pavel-krivanek** [ObjectProfile/Roassal2#34]
<a href="https://github.com/bergel"><img src="https://avatars0.githubusercontent.com/u/393742?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [bergel](https://github.com/bergel)**
_Thursday Aug 03, 2017 at 00:27 GMT_
_Originally opened as https://github.com/moosetechnology/Moose/issues/1254_

----

We need something like:

```Smalltalk
g := RTGrapher new.

d1 := RTData new.
d1 noDot .
d1 connectColor: Color blue.
d1 points: #(1 2 4 5 6 10).
d1 y: #yourself.
g add: d1.

d1 := RTData new.
d1 noDot .
d1 connectColor: Color red.
d1 points: #(1 -3 3 5 9 10).
d1 y: #yourself.
g add: d1.

g addDecorator: (RTContinuousPopup ...)

g
```

**Comment by pavel-krivanek** [comment]
<a href="https://github.com/akevalion"><img src="https://avatars0.githubusercontent.com/u/10532890?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [akevalion](https://github.com/akevalion)**
_Saturday Aug 19, 2017 at 15:00 GMT_

----

I have added a new class RTContinuousDecorator, you can use it in different ways

g := RTGrapher new.

d1 := RTData new.
d1 noDot .
d1 connectColor: Color blue.
d1 points: #(1 2 4 5 6 10).
d1 y: #yourself.
g add: d1.

d1 := RTData new.
d1 noDot .
d1 connectColor: Color red.
d1 points: #(1 -3 3 5 9 10).
d1 y: #yourself.
g add: d1.

g addDecorator: (RTContinuousDecorator new).

g

<img width="324" alt="captura de pantalla 2017-08-18 a la s 20 06 59" src="https://user-images.githubusercontent.com/10532890/29480717-d7ab1d6a-8450-11e7-9f6a-85214af21342.png">

**Comment by pavel-krivanek** [comment]
<a href="https://github.com/bergel"><img src="https://avatars0.githubusercontent.com/u/393742?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [bergel](https://github.com/bergel)**
_Monday Sep 25, 2017 at 23:51 GMT_

----

Looks great, but the continuous decorator should also give the model, in addition to the y value.
For example:
```Smalltalk
g := RTGrapher new.

d1 := RTData new.
d1 noDot .
d1 connectColor: Color blue.
d1 points: ((RTObject withAllSubclasses sortedAs: #numberOfMethods) last: 50).
d1 y: #numberOfMethods.
g add: d1.

d1 := RTData new.
d1 noDot .
d1 connectColor: Color red.
d1 points: ((TRObject withAllSubclasses sortedAs: #numberOfMethods) last: 50).
d1 y: #numberOfMethods.
g add: d1.

g addDecorator: (RTContinuousDecorator new).

g
```
I would expect to see the element for which the mouse is pointing to...

**Comment by bergel** [comment]
Here is an example

```Smalltalk
data1 := (Collection withAllSubclasses) reverseSortedAs: #numberOfMethods.
data2 := (TRShape withAllSubclasses) reverseSortedAs: #numberOfMethods.

g := RTGrapher new.

d1 := RTData new.
d1 noDot .
d1 connectColor: Color blue.
d1 points: data1.
d1 y: #numberOfMethods.
g add: d1.

d1 := RTData new.
d1 noDot .
d1 connectColor: Color red.
d1 points: data2.
d1 y: #numberOfMethods.
g add: d1.

g addDecorator: (RTContinuousDecorator new).

g
```

Indeed, the issue can be closed
