### ISSUE TITLE
We should have violin plot in Roassal

### ISSUE THREAD

**Issue by pavel-krivanek** [ObjectProfile/Roassal2#35]
<a href="https://github.com/bergel"><img src="https://avatars0.githubusercontent.com/u/393742?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [bergel](https://github.com/bergel)**
_Thursday Nov 09, 2017 at 11:33 GMT_
_Originally opened as https://github.com/moosetechnology/Moose/issues/1271_

----

https://datavizcatalogue.com/methods/violin_plot.html

**Comment by pavel-krivanek** [comment]
<a href="https://github.com/lukego"><img src="https://avatars0.githubusercontent.com/u/13791?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [lukego](https://github.com/lukego)**
_Friday Nov 10, 2017 at 10:23 GMT_

----

Just wanted to share my favourite plot lately: [ECDF with confidence band](http://rpubs.com/lukego/300564).

I see a family of plots here:
- Density plot: Show best guess distribution, but has no confidence information.
- Violin plot: Show best guess distribution, plus parametric confidence for comparing averages.
- Banded (E)CDF: Show the set of likely distributions, with no parametric assumptions.

For my work in comparing software performance across a range of benchmarks I have found the last option by far the best. Density plot breaks down because I need the confidence interval (i.e. do I have enough data to draw an inference) and Violin plot doesn't fit because the data is not homogenous(?) enough to be summarized by statistics like mean/median/quartiles.

Some more background at https://stats.stackexchange.com/questions/298290/plotting-non-parametric-ecdef-confidence-envelopes-for-comparison. The confidence bands are actually surprisingly easy to compute.

Sorry to distract from the awesome work you guys are doing! :-)

**Comment by akevalion** [comment]
Moved to roassal3
