### ISSUE TITLE
Making RTDraggableView customizable

### ISSUE THREAD

**Issue by pavel-krivanek** [ObjectProfile/Roassal2#36]
<a href="https://github.com/bergel"><img src="https://avatars0.githubusercontent.com/u/393742?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [bergel](https://github.com/bergel)**
_Tuesday Nov 21, 2017 at 00:33 GMT_
_Originally opened as https://github.com/moosetechnology/Moose/issues/1272_

----

Peter asked: is there a way to modify RTDraggableView to support dragging via middle click or left click?

**Comment by peteruhnak** [comment]
I've used `RTSelectableView` to solve this, so as far as I am concerned this issue can be closed.

**Comment by bergel** [comment]
Actually, the feature has been implemented. 
You can do:
```
	| v |
	v := RTView new.
	v @ RTDraggableView new right.
	RTCPDiverging new viewOn: v.
	^ v
```
