### ISSUE TITLE
Using Foreign objects when exporting SVG

### ISSUE THREAD

**Issue by pavel-krivanek** [ObjectProfile/Roassal2#37]
<a href="https://github.com/bergel"><img src="https://avatars0.githubusercontent.com/u/393742?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [bergel](https://github.com/bergel)**
_Monday Dec 11, 2017 at 14:30 GMT_
_Originally opened as https://github.com/moosetechnology/Moose/issues/1273_

----

Dusty on Discord suggested to use foreign objects. He says:
"creating SVG for web interfacces, like I'm doing the graphical rendering in roassal, but exporting the SVG to a web interface. I'd like to make the blocks clickable (via <a ...> tag) to open properties of the item in the web app"
"also, forienobject would allow for title= or <title> tag for hover"

We should have a look at this.

**Comment by akevalion** [comment]
moved to roassal3exporters
Please use roassal3 https://github.com/ObjectProfile/Roassal3
I will close this issue because cleaning process and roassal2 will be frozen
