### ISSUE TITLE
Making a grapher draggable

### ISSUE THREAD

**Issue by pavel-krivanek** [ObjectProfile/Roassal2#38]
<a href="https://github.com/bergel"><img src="https://avatars0.githubusercontent.com/u/393742?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [bergel](https://github.com/bergel)**
_Wednesday May 02, 2018 at 17:16 GMT_
_Originally opened as https://github.com/moosetechnology/Moose/issues/1293_

----

Increating the 30 to 100 does not show anything. We should be able to drag the background and see the graph content and the axes adjusted accordingly.

```Smalltalk
r := Random seed: 10.
data := OrderedCollection new.
1 to: 30 do: [:i | | datum r1 r2 |
    r1 := r next * 100.
    r2 := r next * 100.
    datum := OrderedCollection with:  ('c',i asString) with: (r1 min: r2) with: (r1 max: r2).
    data add: datum
].    
b := RTTimeline new.
s := RTTimelineSet new.
s objects: data.
s lineIdentifier: #first.
s start: #second.
s end: #third.
b add: s.
b axisX
    numberOfLabels: 15;
    labelRotation: -45;
    labelConversion: [ :v | v ceiling ].
b build.
^ b view
```

**Comment by akevalion** [comment]
No longer valid
Please use roassal3 https://github.com/ObjectProfile/Roassal3
I will close this issue because cleaning process and roassal2 will be frozen
