### ISSUE TITLE
Add color configuration to horizontal decorators in Grapher

### ISSUE THREAD

**Issue by dorellang** [ObjectProfile/Roassal2#50]
Hi, trying to do some graphs for my graduation project I've found that whereas the vertical decorators do support color settings (via the RTAbstractVerticalValuesDecorator>>#labelColor: accessor), the horizontal decorators don't :disappointed:

I think this shouldn't be that hard, just adding the corresponding instance var and accessors for RTAbstractHorizontalValuesDecorator>>#labelColor: and actually using them for rendering should do the trick. Maybe I'll make a Pull Request when I have more time (or maybe not lol).

**Comment by akevalion** [comment]
You can find this behaviour in RSVerticalTick and RSHorizontalTick in roassal3

Please use roassal3 https://github.com/ObjectProfile/Roassal3
I will close this issue because cleaning process and roassal2 will be frozen
