### ISSUE TITLE
OpenStreetMap Examples - Wrong Fuel Version

### ISSUE THREAD

**Issue by seandenigris** [ObjectProfile/Roassal2#57]
`RTOSM buildingsAndStreamKampungMelayu` -> expecting 193 but got 194

**Comment by seandenigris** [comment]
@bergel Are Roassal 2 issues still being worked on? If so, is this one worth looking at?

**Comment by bergel** [comment]
Hi Sean,

You are raising a good question. To tell you the truth, it is unlikely that we focus on addressing Roassal2 issues. We are focusing on Roassal 3 these days. I leave this issue open anyway. In case we migrate OpenStreetMap to Roassal3 (which I would like to see), then we we will surely address it.

**Comment by akevalion** [comment]
No longer valid
RTOSM is not present in roassal3 yet, but we will work on that
Please use roassal3 https://github.com/ObjectProfile/Roassal3
I will close this issue because cleaning process and roassal2 will be frozen
