### ISSUE TITLE
Roassal2 loading is broken in Pharo 8

### ISSUE THREAD

**Issue by jecisc** [ObjectProfile/Roassal2#58]
The class RTEventRegister uses a class that was removed from Pharo 8 so Roassal cannot load anymore in Pharo 8.

**Comment by bergel** [comment]
Thanks @jecisc !
We removed the dependency. Roassal2 should load in Pharo 8 without any problem.

**Comment by sebastianconcept** [comment]
I've loaded it in Pharo 9 today, I think we can close this issue now.

**Comment by akevalion** [comment]
Please use roassal3 https://github.com/ObjectProfile/Roassal3
I will close this issue because cleaning process and roassal2 will be frozen
