### ISSUE TITLE
RTSVGExporter subscript out of bounds if it doesn't contain any shapes

### ISSUE THREAD

**Issue by hernanmd** [ObjectProfile/Roassal2#7]
When doing mass exporting of figures using RTSVGExporter some of them could be empty. It would be nice to have a method to check this condition, for example: hasShapes or to allow exporting empty figures

See screenshot for details:

![rtsvgexporter](https://user-images.githubusercontent.com/4825959/45266893-e7819e80-b438-11e8-878f-08204b4c5f8a.png)

**Comment by akevalion** [comment]
I have change the code, but Roassal2 will be frozen.
Please use roassal3 https://github.com/ObjectProfile/Roassal3
